import java.util.Arrays;
import java.util.Random;
import java.lang.reflect.Array;

/**
 * Sorting class including all sorting algorithms
 * discussed in the course. The goal of this is to
 * explore with different set of values and see
 * how different sort routines perform better.
 * 
 * Full disclosure: initial code generated by ChatGPT.
 */
public class Sorting {
    private static int numComparisons;
    private static int numMoves;

    /**
     * Compares neighboring items and swaps them if
     * needed. Each pass moves the largest remaining
     * item to the end. Looks like bubbling items up
     * to the top.
     * 
     * @param arr array of numbers to sort
     */

    public static <E extends Comparable<E>> void bubbleSort(E[] arr) {
        int n = arr.length;

        // Outer loop for passes
        for (int i = 0; i < n - 1; i++) {

            // Inner loop for comparisons
            for (int j = 0; j < n - i - 1; j++) {
                numComparisons++;
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    // Swap if out of order
                    E temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                    numMoves += 3;
                }
            }
        }
    }

    /**
     * Enhanced bubble sort, stops comparing once all
     * numbers are already ordered. Compares neighboring
     * items and swaps them if needed. Each pass moves
     * the largest remaining item to the end. Looks
     * like bubbling items up to the top.
     * 
     * @param arr array of numbers to sort
     */
    public static <E extends Comparable<E>> void bubbleSort2(E[] arr) {
        boolean swapped;

        // Outer loop for passes
        for (int i = 0; i < arr.length - 1; i++) {
            swapped = false;

            // Inner loop for comparisons
            for (int j = 0; j < arr.length - i - 1; j++) {
                numComparisons++;
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    // Swap if out of order
                    E temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                    numMoves += 3;
                    swapped = true;
                }
            }

            // If no swaps happened, array is already sorted
            if (!swapped)
                break;
        }
    }

    /**
     * Builds the sorted list one item at a time by
     * inserting each new item into its correct position
     * among the already-sorted items. Like sorting
     * cards in your hand.
     * 
     * @param arr array of numbers to sort
     */
    public static <E extends Comparable<E>> void insertionSort(E[] arr) {

        for (int i = 1; i < arr.length; i++) {
            E key = arr[i]; // The item to insert
            numMoves++;
            int j = i - 1;

            // Shift larger elements to the right
            while (j >= 0 && arr[j].compareTo(key) > 0) {
                numComparisons++;
                arr[j + 1] = arr[j];
                numMoves++;
                j--;
            }

            // Insert the key at the correct position
            if (j >= 0)
                numComparisons++; // adjustment for undercount 1
            arr[j + 1] = key;
            numMoves++;
        }
    }

    /**
     * Repeatedly finds the smallest remaining item and
     * moves it directly to its correct final position.
     * Few swaps, lots of searching.
     * 
     * @param arr array of numbers to sort
     */
    public static <E extends Comparable<E>> void selectionSort(E[] arr) {
        int n = arr.length;

        // Move boundary of unsorted subarray
        for (int i = 0; i < n - 1; i++) {
            // Assume the minimum is the first element
            int minIndex = i;

            // Find the actual minimum in the unsorted part
            for (int j = i + 1; j < n; j++) {
                numComparisons++;
                if (arr[j].compareTo(arr[minIndex]) < 0) {
                    minIndex = j;
                }
            }

            // Swap the found minimum with the first unsorted element
            E temp = arr[minIndex];
            arr[minIndex] = arr[i];
            arr[i] = temp;
            numMoves += 3;
        }
    }

    /**
     * Entry point for the quicksort routine.
     * 
     * @param arr array of numbers to sort
     */
    public static <E extends Comparable<E>> void quickSort(E[] arr) {
        quickSort(arr, 0, arr.length - 1);
    }

    /**
     * Picks a pivot item, puts smaller items on one side,
     * larger items on the other, then repeats on each side.
     * Partitions the list into smaller pieces.
     * 
     * @param arr array of numbers to sort
     */
    public static <E extends Comparable<E>> void quickSort(E[] arr, int low, int high) {
        if (low < high) {
            // Partition the array, arr[pi] is now in the right place
            int pi = partition(arr, low, high);

            // Recursively sort elements before and after partition
            quickSort(arr, low, pi - 1);
            quickSort(arr, pi + 1, high);
        }
    }

    /**
     * Partition routine for the quicksort routine.
     * 
     * @param arr  array of numbers to sort
     * @param low  left index of the partition
     * @param high right index of the partition
     */
    private static <E extends Comparable<E>> int partition(E[] arr, int low, int high) {
        E pivot = arr[high]; // Choose last element as pivot
        numMoves++;
        int i = low - 1; // Index of smaller element

        for (int j = low; j < high; j++) {
            numComparisons++;
            if (arr[j].compareTo(pivot) <= 0) {
                i++;
                // Swap arr[i] and arr[j]
                E temp = arr[i];
                arr[i] = arr[j];
                arr[j] = temp;
                numMoves += 3;
            }
        }

        // Place pivot in correct position
        E temp = arr[i + 1];
        arr[i + 1] = arr[high];
        arr[high] = temp;
        numMoves += 3;

        return i + 1;
    }

    /**
     * Entry point for the merge sort routine.
     * 
     * @param arr array of numbers to sort
     */
    public static <E extends Comparable<E>> void mergeSort(E[] arr) {
        mergeSort(arr, 0, arr.length - 1);
    }

    /**
     * Divides the list into halves until each piece is
     * tiny, then merges the pieces back together in order.
     * Splitting down, merging up.
     * 
     * @param arr   array of numbers to sort
     * @param left  index of the partition
     * @param right index of the partition
     */
    public static <E extends Comparable<E>> void mergeSort(E[] arr, int left, int right) {
        if (left < right) {
            int mid = (left + right) / 2;

            // Sort first half
            mergeSort(arr, left, mid);
            // Sort second half
            mergeSort(arr, mid + 1, right);

            // Merge the two halves
            merge(arr, left, mid, right);
        }
    }

    /**
     * Merges the two halfs of the partitioned array.
     * 
     * @param arr   array of numbers to sort
     * @param left  index of the partition
     * @param mid   index of the partition
     * @param right index of the partition
     */
    @SuppressWarnings("unchecked")
    private static <E extends Comparable<E>> void merge(E[] arr, int left, int mid, int right) {
        // Sizes of subarrays
        int n1 = mid - left + 1;
        int n2 = right - mid;

        // Temp arrays
        // E[] L = (E[]) new Object[n1];
        E[] L = (E[]) Array.newInstance(
                arr.getClass().getComponentType(),
                n1);
        // E[] R = (E[]) new Object[n2];
        E[] R = (E[]) Array.newInstance(
                arr.getClass().getComponentType(),
                n2);

        // Copy data
        for (int i = 0; i < n1; i++) {
            numMoves++;
            L[i] = arr[left + i];
        }
        for (int j = 0; j < n2; j++) {
            numMoves++;
            R[j] = arr[mid + 1 + j];
        }

        // Merge the temp arrays
        int i = 0, j = 0;
        int k = left;

        while (i < n1 && j < n2) {
            numComparisons++;
            if (L[i].compareTo(R[j]) <= 0) {
                numMoves++;
                arr[k] = L[i];
                i++;
            } else {
                numMoves++;
                arr[k] = R[j];
                j++;
            }
            k++;
        }

        // Copy remaining elements
        while (i < n1) {
            numMoves++;
            arr[k] = L[i];
            i++;
            k++;
        }
        while (j < n2) {
            numMoves++;
            arr[k] = R[j];
            j++;
            k++;
        }
    }

    /**
     * Routine to start the data collection of
     * comparisons and data moves for each
     * sorting routine. It resets counters to 0
     * and restores the data to be sorted to the
     * same original array for better comparisons.
     */
    public static <E extends Comparable<E>> E[] startCollection(E[] testCase) {
        numComparisons = 0;
        numMoves = 0;
        // E[] numbers = (E[]) new Object[testCase.length];
        E[] numbers = Arrays.copyOf(testCase, testCase.length);

        for (int i = 0; i < testCase.length; i++)
            numbers[i] = testCase[i];
        return numbers;
    }

    /**
     * Routine to print out the results of the
     * data collection of a sorting routine.
     */
    public static <E extends Comparable<E>> void endCollection(String sort, E[] numbers) {
        System.out.println("After " + sort);
        for (E num : numbers) {
            System.out.print(num + " ");
        }
        System.out.println("\n");
        System.out.println("Number of comparisons: " + numComparisons);
        System.out.println("Number of moves: " + numMoves);
        System.out.println("----------------------");
    }

    /**
     * Run a test case.
     */
    public static <E extends Comparable<E>> void runTestCase(String test, E[] testCase) {
        E[] numbers;
        System.out.println("\n\n----------------------");
        System.out.println("- " + test);
        System.out.println("----------------------");
        System.out.println("Before sorting");
        for (E num : testCase) {
            System.out.print(num + " ");
        }
        System.out.println("\n----------------------");

        numbers = startCollection(testCase);
        Sorting.bubbleSort(numbers);
        endCollection("Bubble sort", numbers);

        numbers = startCollection(testCase);
        Sorting.bubbleSort2(numbers);
        endCollection("Bubble (improved) sort", numbers);

        numbers = startCollection(testCase);
        Sorting.insertionSort(numbers);
        endCollection("Insertion sort", numbers);

        numbers = startCollection(testCase);
        Sorting.selectionSort(numbers);
        endCollection("Selection sort", numbers);

        numbers = startCollection(testCase);
        Sorting.quickSort(numbers);
        endCollection("QuickSort", numbers);

        numbers = startCollection(testCase);
        Sorting.mergeSort(numbers);
        endCollection("Merge sort", numbers);

    }

    /**
     * Main program that creates a data set, and
     * collects data on each of the sorting routines.
     * 
     * @param args command line arguments - not used
     */
    public static void main(String[] args) {
        Random rand = new Random();
        Integer[] testCase;

        int size = 25;
        testCase = new Integer[size];
        for (int i = 0; i < testCase.length; i++)
            testCase[i] = rand.nextInt(1000);

        runTestCase("Random data", testCase);

        // Create random numbers in increasing order and test case
        Integer[] caseSorted = new Integer[25];
        int caseStart = 0;
        for (int i = 0; i < caseSorted.length; i++) {
            caseSorted[i] = caseStart;
            caseStart += 10;
        }
        runTestCase("Increasing order", caseSorted);

        // Create random numbers in decreasing order and test case
        Integer[] caseReverse = new Integer[25];
        caseStart = 200;
        for (int i = 0; i < caseReverse.length; i++) {
            caseReverse[i] = caseStart;
            caseStart -= 10;
        }
        runTestCase("deceasing order", caseReverse);

    }
}
